%% manually load .mat files generated by beta_plots.m, then run the following lines

%greenish color for recent, yellowish color for lifetime

%% lifetime dec-rele
bar(categorical([1:1:5]),[life1_avg,life2_avg,life3_avg,life4_avg,life5_avg],'FaceColor','#FFC000');
hold on
er=errorbar(categorical([1:1:5]),[life1_avg,life2_avg,life3_avg,life4_avg,life5_avg],[life1_se,life2_se,life3_se,life4_se,life5_se],'Color','w');
er.LineStyle = 'none';
xlabel('lifetime ratings');
ylabel('average beta value');
set(gca,'Color','k');
set(gcf,'Color','k');
set(gca,'XColor','w');
set(gca,'YColor','w');
set(gca,'FontSize',13);
box off
hold off
set(gcf, 'InvertHardcopy', 'off')


%% recent dec-rele
bar(categorical([1:1:5]),[recent1_avg,recent2_avg,recent3_avg,recent4_avg,recent5_avg],'FaceColor','#40C000');
hold on
er=errorbar(categorical([1:1:5]),[recent1_avg,recent2_avg,recent3_avg,recent4_avg,recent5_avg],[recent1_se,recent2_se,recent3_se,recent4_se,recent5_se],'Color','w');
er.LineStyle = 'none';
xlabel('frequency ratings');
ylabel('average beta value');
set(gca,'Color','k');
set(gcf,'Color','k');
set(gca,'XColor','w');
set(gca,'YColor','w');
set(gca,'FontSize',13);
box off
hold off
set(gcf, 'InvertHardcopy', 'off')


%% rep-sup (pres1>789)
bar(categorical({'pres1','pres7','pres8','pres9'}),[pres1_avg,pres7_avg,pres8_avg,pres9_avg],'FaceColor','#40C000');
hold on
er=errorbar(categorical({'pres1','pres7','pres8','pres9'}),[pres1_avg,pres7_avg,pres8_avg,pres9_avg],[pres1_se,pres7_se,pres8_se,pres9_se],'Color','w');
er.LineStyle = 'none';
xlabel('presentation number')
ylabel('average beta value');
set(gca,'Color','k');
set(gcf,'Color','k');
set(gca,'XColor','w');
set(gca,'YColor','w');
set(gca,'FontSize',13);
box off
hold off
set(gcf, 'InvertHardcopy', 'off')


%% lifetime dec-irr testphase
bar(categorical([1:1:5]),[life_irr_1_avg,life_irr_2_avg,life_irr_3_avg,life_irr_4_avg,life_irr_5_avg],'FaceColor','#FFC000');
hold on
er=errorbar(categorical([1:1:5]),[life_irr_1_avg,life_irr_2_avg,life_irr_3_avg,life_irr_4_avg,life_irr_5_avg],[life_irr_1_se,life_irr_2_se,life_irr_3_se,life_irr_4_se,life_irr_5_se],'Color','w');
er.LineStyle = 'none';
xlabel('lifetime ratings');
ylabel('average beta value');
set(gca,'Color','k');
set(gcf,'Color','k');
set(gca,'XColor','w');
set(gca,'YColor','w');
set(gca,'FontSize',13);
box off
hold off
set(gcf, 'InvertHardcopy', 'off')

%% studyphase lifetime all trials
bar(categorical([1:1:5]),[life1_avg,life2_avg,life3_avg,life4_avg,life5_avg],'FaceColor','#FFC000');
hold on
er=errorbar(categorical([1:1:5]),[life1_avg,life2_avg,life3_avg,life4_avg,life5_avg],[life1_se,life2_se,life3_se,life4_se,life5_se],'Color','w');
er.LineStyle = 'none';
xlabel('lifetime ratings');
ylabel('average beta value');
set(gca,'Color','k');
set(gcf,'Color','k');
set(gca,'XColor','w');
set(gca,'YColor','w');
set(gca,'FontSize',13);
box off
hold off
set(gcf, 'InvertHardcopy', 'off')

%% studyphase lifetime pres1
bar(categorical([1:1:5]),[life1_avg,life2_avg,life3_avg,life4_avg,life5_avg],'FaceColor','#FFC000');
hold on
er=errorbar(categorical([1:1:5]),[life1_avg,life2_avg,life3_avg,life4_avg,life5_avg],[life1_se,life2_se,life3_se,life4_se,life5_se],'Color','w');
er.LineStyle = 'none';
xlabel('lifetime ratings');
ylabel('average beta value');
set(gca,'Color','k');
set(gcf,'Color','k');
set(gca,'XColor','w');
set(gca,'YColor','w');
set(gca,'FontSize',13);
box off
hold off
set(gcf, 'InvertHardcopy', 'off')

