#!/bin/bash
usage(){
echo "run joblist created by genjob
 usage: submit_joblist <joblist.txt>"
}
joblist=$1
if [ "$#" -eq 1 ]; then
	while IFS= read -r line; do
	regularSubmit "$line"
	sleep 3
	done < "$joblist"
else
usage
exit 1
fi
