#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=4000
#SBATCH --time=72:00:00
#SBATCH --job-name=neurogliaSubmit
#SBATCH --account=rrg-akhanf
#SBATCH --output=/project/6007967/hyang336/matlab/PPCMD_git/PPCPRC/analyses/pilot/jobs/neurogliaSubmit.%A.out
echo SINGULARITY_IMG: /project/6007967/akhanf/singularity/akhanf-vasst-dev-master-v0.0.4g.simg
echo CMD: matlab -nosplash -nodisplay -r "addpath(genpath('/project/6007967/hyang336/matlab/')); lifetime180('/home/hyang336/projects/rrg-akhanf/cfmm-deriv/Kohler/PPC_MD/','/home/hyang336/projects/rrg-akhanf/cfmm-deriv/Kohler/PPC_MD/','sub-003',5,'fmriprep1.3.2_dual-echo-summed',1.65); exit;"
echo START_TIME: `date`
export SCRATCH_DIR=/scratch/hyang336/${SLURM_JOB_ID}
mkdir -p $SCRATCH_DIR
cd /home/hyang336/home/matlab/PPCMD_git/PPCPRC/analyses/pilot
singularity exec -e -B /cvmfs:/cvmfs -B /project:/project -B /scratch:/scratch -B /localscratch:/localscratch /project/6007967/akhanf/singularity/akhanf-vasst-dev-master-v0.0.4g.simg matlab -nosplash -nodisplay -r "addpath(genpath('/project/6007967/hyang336/matlab/')); lifetime180('/home/hyang336/projects/rrg-akhanf/cfmm-deriv/Kohler/PPC_MD/','/home/hyang336/projects/rrg-akhanf/cfmm-deriv/Kohler/PPC_MD/','sub-003',5,'fmriprep1.3.2_dual-echo-summed',1.65); exit;"
RETURNVAL=$?
rm -rf $SCRATCH_DIR
echo RETURNVAL=$RETURNVAL
echo END_TIME: `date`
exit $RETURNVAL
